/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_videogame_80s.interfaces;

import java_videogame_80s.gamecomponents.EspacioJuego;

/**
 *
 * @author juanq
 */
public class InterfazPrincipal extends javax.swing.JPanel {

    private MenuActions menuActions; 
    
    public InterfazPrincipal() {
        this.menuActions = menuActions; 
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_layout = new javax.swing.JLabel();
        bar1 = new javax.swing.JLabel();
        circle = new javax.swing.JLabel();
        aboutus_button = new javax.swing.JPanel();
        aboutus_title = new javax.swing.JLabel();
        empezar_button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 52, 60));
        setPreferredSize(new java.awt.Dimension(800, 500));

        title_layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/title_layour.png"))); // NOI18N

        bar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/Bar.jpg"))); // NOI18N

        circle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/Circle.png"))); // NOI18N

        aboutus_button.setBackground(new java.awt.Color(52, 52, 60));

        aboutus_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Icons/about us.png"))); // NOI18N
        aboutus_button.add(aboutus_title);

        empezar_button.setBackground(new java.awt.Color(155, 152, 152));
        empezar_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empezar_buttonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("EMPEZAR");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Icons/play.png"))); // NOI18N

        javax.swing.GroupLayout empezar_buttonLayout = new javax.swing.GroupLayout(empezar_button);
        empezar_button.setLayout(empezar_buttonLayout);
        empezar_buttonLayout.setHorizontalGroup(
            empezar_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empezar_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        empezar_buttonLayout.setVerticalGroup(
            empezar_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empezar_buttonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(empezar_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(bar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empezar_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aboutus_button, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(title_layout, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(circle)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aboutus_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title_layout, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(circle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bar1)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(empezar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        empezar_button.getAccessibleContext().setAccessibleName("empezar");
    }// </editor-fold>//GEN-END:initComponents

    private void empezar_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empezar_buttonMouseClicked
        EspacioJuego espacioJuego = new EspacioJuego(); 
        espacioJuego.setVisible(true);
        menuActions.closeMainMenu();
    }//GEN-LAST:event_empezar_buttonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutus_button;
    private javax.swing.JLabel aboutus_title;
    private javax.swing.JLabel bar1;
    private javax.swing.JLabel circle;
    private javax.swing.JPanel empezar_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel title_layout;
    // End of variables declaration//GEN-END:variables
}
