package interfaces;

import Utils.CustomFont;
import Utils.Hilo;
import gamecomponents.GameSpace;
import gamecomponents.KeyEvents;
import Utils.LectorCSV;
import Utils.PlaySounds;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class ControlInterface extends javax.swing.JFrame {

    private final int ALTO = 600, ANCHO = 900;
    private GameSpace espacioDeJuego;
    private Hilo hilo;
    private LectorCSV csv;
    private boolean bPause;
    private boolean music;

    public ControlInterface() {
        initComponents();
        this.setSize(ANCHO, ALTO);
        this.setLocationRelativeTo(null);
        bPause = false;
        music = true;
        gameOver.setSize(ANCHO, ALTO);
        gameOver.setLocationRelativeTo(null);
        pause.setSize(ANCHO, ALTO);
        this.setFocusable(true);
        this.setResizable(false);
        espacioDeJuego = new GameSpace(this);
        espacioDeJuego.setBounds(0, 0, ANCHO - 200, ALTO);
        this.add(espacioDeJuego);
        addKeyListener(new KeyEvents(this));
        hilo = new Hilo(espacioDeJuego);
        hilo.start();
        readScore();
    }

    public JFrame getGameOver() {
        return gameOver;
    }

    public Hilo getHilo() {
        return hilo;
    }

    public JLabel getBalls() {
        return numberOfBalls;
    }

    public JLabel getScore() {
        return scoreViewr;
    }

    public void setbPause(boolean bPause) {
        this.bPause = bPause;
    }

    public void writeScore(String username, String score) {
        String sDir = "C:\\user";
        File f = new File(sDir);
        String fileName = "score.txt";
        File file = new File(sDir, fileName);

        if (!file.exists()) {
            f.mkdir();
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(ControlInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try (FileWriter fw = new FileWriter(file.getAbsoluteFile(), true)) {
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(username + "," + score);
            bw.newLine();
            bw.flush();
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(ControlInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void readScore() {
        String sDir = "C:\\user";
        File f = new File(sDir);
        String fileName = "score.txt";
        File file = new File(sDir, fileName);

        if (!file.exists()) {
            f.mkdir();
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(ControlInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        csv = new LectorCSV(file.getAbsolutePath());
        csv.organizar();
        LectorCSV.ObjectCSV[] o = csv.getObjetos();

        for (int i = 0; i < 6; i++) {
            if (o.length > i) {
                if (o[i] != null) {
                    if (i != 0) {
                        leaderBoard.setText(leaderBoard.getText() + "\n" + o[i].getUsernarme());
                    } else {
                        leaderBoard.setText(o[i].getUsernarme());
                    }
                }
            }
        }
    }

    public void pause() {
        if (!bPause) {
            if (music) {
                espacioDeJuego.getBgMusic().loop(-1);
            }
            hilo.resume();
            hilo.reanudar();
            espacioDeJuego.setJuego(true);
            bPause = true;
            pause.setVisible(false);
            espacioDeJuego.setFocusable(true);
        } else {
            if (music) {
                espacioDeJuego.getBgMusic().stop();
            }
            hilo.suspend();
            hilo.pause();
            bPause = false;
            pause.setVisible(true);
            espacioDeJuego.setFocusable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameOver = new javax.swing.JFrame();
        gameover = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        Settings = new javax.swing.JDialog(this, true);
        changeColorbtn = new javax.swing.JButton();
        restartbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pause = new javax.swing.JPanel();
        pauseTitle = new javax.swing.JLabel();
        controls = new javax.swing.JPanel();
        settingbtn = new javax.swing.JButton();
        x = new javax.swing.JLabel();
        ball = new javax.swing.JLabel();
        numberOfBalls = new javax.swing.JLabel();
        leaderBoardTitle = new javax.swing.JLabel();
        leaderBoard = new javax.swing.JTextArea();
        scoreViewr = new javax.swing.JLabel();
        scoreTitle = new javax.swing.JLabel();
        musicbtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        gameOver.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        gameOver.setFocusable(false);
        gameOver.setUndecorated(true);
        gameOver.setOpacity(0.5F);
        gameOver.getContentPane().setLayout(null);

        gameover.setFont(new CustomFont("pdark.ttf").font(1, 60f));
        gameover.setText("Game Over");
        gameOver.getContentPane().add(gameover);
        gameover.setBounds(180, 10, 540, 230);

        reset.setFont(new CustomFont("pdark.ttf").font(1, 15f));
        reset.setText("VOLVER A JUGAR");
        reset.setFocusable(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        gameOver.getContentPane().add(reset);
        reset.setBounds(190, 420, 230, 70);

        jLabel4.setFont(new CustomFont("pdark.ttf").font(1, 30f));
        jLabel4.setText("Username");
        gameOver.getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 270, 90);

        username.setBackground(gameOver.getBackground());
        username.setFont(new CustomFont("pdark.ttf").font(1,30f));
        gameOver.getContentPane().add(username);
        username.setBounds(320, 220, 510, 70);

        Settings.setBounds(new java.awt.Rectangle(0, 0, 400, 200));
        Settings.setPreferredSize(new java.awt.Dimension(400, 200));
        Settings.setResizable(false);
        Settings.getContentPane().setLayout(null);

        changeColorbtn.setText("Cambiar Colores de Ladrillos");
        changeColorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeColorbtnActionPerformed(evt);
            }
        });
        Settings.getContentPane().add(changeColorbtn);
        changeColorbtn.setBounds(10, 110, 180, 50);

        restartbtn.setText("Reiniciar Juego");
        restartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartbtnActionPerformed(evt);
            }
        });
        Settings.getContentPane().add(restartbtn);
        restartbtn.setBounds(220, 110, 140, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Configuracion");
        Settings.getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 40, 141, 25);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AlleyWay");
        getContentPane().setLayout(null);

        pause.setAlignmentX(0.0F);
        pause.setAlignmentY(0.0F);
        pause.setFocusable(false);
        pause.setOpaque(false);
        pause.setLayout(null);

        pauseTitle.setFont(new CustomFont("pdark.ttf").font(1,30f));
        pauseTitle.setForeground(new java.awt.Color(255, 255, 0));
        pauseTitle.setText("Pause");
        pause.add(pauseTitle);
        pauseTitle.setBounds(240, 170, 260, 190);

        getContentPane().add(pause);
        pause.setBounds(0, 0, 900, 600);

        controls.setBackground(new java.awt.Color(0, 0, 0));
        controls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        controls.setLayout(null);

        settingbtn.setBackground(new java.awt.Color(156, 155, 155));
        settingbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataIcons/settings.png"))); // NOI18N
        settingbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingbtn.setFocusPainted(false);
        settingbtn.setFocusable(false);
        settingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingbtnActionPerformed(evt);
            }
        });
        controls.add(settingbtn);
        settingbtn.setBounds(140, 10, 50, 40);

        x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        x.setForeground(new java.awt.Color(153, 153, 153));
        x.setText("x");
        controls.add(x);
        x.setBounds(60, 160, 30, 30);

        ball.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataImages/Circle.png"))); // NOI18N
        controls.add(ball);
        ball.setBounds(20, 150, 40, 40);

        numberOfBalls.setFont(new CustomFont("ARCADE_I.TTF").font(1,15f));
        numberOfBalls.setForeground(new java.awt.Color(153, 153, 153));
        controls.add(numberOfBalls);
        numberOfBalls.setBounds(80, 150, 90, 50);

        leaderBoardTitle.setFont(new CustomFont("ARCADE_I.TTF").font(1,13f));
        leaderBoardTitle.setForeground(new java.awt.Color(153, 153, 153));
        leaderBoardTitle.setText("LeaderBoard");
        controls.add(leaderBoardTitle);
        leaderBoardTitle.setBounds(20, 210, 180, 50);

        leaderBoard.setBackground(new java.awt.Color(0, 0, 0));
        leaderBoard.setColumns(20);
        leaderBoard.setFont(new CustomFont("ARCADE_I.TTF").font(1,15f));
        leaderBoard.setForeground(new java.awt.Color(153, 153, 153));
        leaderBoard.setRows(5);
        leaderBoard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        leaderBoard.setEnabled(false);
        leaderBoard.setFocusable(false);
        controls.add(leaderBoard);
        leaderBoard.setBounds(20, 260, 164, 260);

        scoreViewr.setFont(new CustomFont("ARCADE_I.TTF").font(1,15f));
        scoreViewr.setForeground(new java.awt.Color(153, 153, 153));
        controls.add(scoreViewr);
        scoreViewr.setBounds(10, 60, 120, 50);

        scoreTitle.setFont(new CustomFont("ARCADE_I.TTF").font(1,15f));
        scoreTitle.setForeground(new java.awt.Color(153, 153, 153));
        scoreTitle.setText("SCORE");
        controls.add(scoreTitle);
        scoreTitle.setBounds(10, 20, 160, 50);

        musicbtn.setBackground(new java.awt.Color(156, 155, 155));
        musicbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataIcons/music.png"))); // NOI18N
        musicbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        musicbtn.setFocusPainted(false);
        musicbtn.setFocusable(false);
        musicbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicbtnActionPerformed(evt);
            }
        });
        controls.add(musicbtn);
        musicbtn.setBounds(140, 60, 50, 40);

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        controls.add(jButton6);
        jButton6.setBounds(140, 120, 50, 23);

        getContentPane().add(controls);
        controls.setBounds(700, 0, 200, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        if (!username.getText().equals("")) {
            gameOver.setVisible(false);
            this.remove(espacioDeJuego);
            espacioDeJuego = new GameSpace(this);
            espacioDeJuego.setBounds(0, 0, ANCHO - 200, ALTO);
            this.add(espacioDeJuego);
            hilo = new Hilo(espacioDeJuego);
            hilo.start();
            writeScore(username.getText(), scoreViewr.getText());
            readScore();
        } else {
            System.out.println("usuario invalido");
        }
    }//GEN-LAST:event_resetActionPerformed

    private void settingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingbtnActionPerformed
        // TODO add your handling code here:
        PlaySounds btnSound = new PlaySounds("src\\dataSounds\\ButtonSound.wav");
        btnSound.getClip().start();
        if (bPause) {
            pause();
        }
        Settings.setBounds(this.getX()+200, this.getY()+200, 400, 200);
        Settings.setVisible(true);
    }//GEN-LAST:event_settingbtnActionPerformed

    private void musicbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicbtnActionPerformed

        if (music) {
            espacioDeJuego.getBgMusic().stop();
            music = false;
        } else {
            espacioDeJuego.getBgMusic().loop(-1);
            music = true;
        }
    }//GEN-LAST:event_musicbtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        espacioDeJuego.nivel.getBricks().clear();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void changeColorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeColorbtnActionPerformed
        // TODO add your handling code here:
        if (!espacioDeJuego.isJuego()) {
            espacioDeJuego.getNivel().cambioColores();
        }
    }//GEN-LAST:event_changeColorbtnActionPerformed

    private void restartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartbtnActionPerformed
        // TODO add your handling code here:
        espacioDeJuego.getBgMusic().close();
        this.espacioDeJuego.getNivel().setSiguiente(null);
        this.espacioDeJuego.getNivel().getBricks().clear();
        this.espacioDeJuego.niveles();
        this.espacioDeJuego.getTable().setX(110);
        this.espacioDeJuego.getBall().setX(160);
        this.espacioDeJuego.getBall().setY(480);
        this.espacioDeJuego.getBall().setCambioX(1);
        this.espacioDeJuego.getBall().setCambioY(-1);
        this.espacioDeJuego.setBalls(3);
        this.espacioDeJuego.setScore(0);
        this.espacioDeJuego.setMaxPoderes(5);
        if (!bPause) {
            this.pause();
        }
        this.espacioDeJuego.setJuego(false);
        this.getHilo().pause();
        this.setbPause(false);
        Settings.dispose();
    }//GEN-LAST:event_restartbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Settings;
    private javax.swing.JLabel ball;
    private javax.swing.JButton changeColorbtn;
    private javax.swing.JPanel controls;
    private javax.swing.JFrame gameOver;
    private javax.swing.JLabel gameover;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextArea leaderBoard;
    private javax.swing.JLabel leaderBoardTitle;
    private javax.swing.JButton musicbtn;
    private javax.swing.JLabel numberOfBalls;
    private javax.swing.JPanel pause;
    private javax.swing.JLabel pauseTitle;
    private javax.swing.JButton reset;
    private javax.swing.JButton restartbtn;
    private javax.swing.JLabel scoreTitle;
    private javax.swing.JLabel scoreViewr;
    private javax.swing.JButton settingbtn;
    private javax.swing.JTextField username;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
