/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author juanq
 */
public class ControlInterface extends javax.swing.JFrame {

    /**
     * Creates new form MenuJuego
     */
    public ControlInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuJuego_content = new javax.swing.JPanel();
        switch_BarVelocity_title = new javax.swing.JLabel();
        switch_BallVelocity_title = new javax.swing.JLabel();
        menu_title = new javax.swing.JPanel();
        menu_tittle = new javax.swing.JLabel();
        restart_button = new javax.swing.JPanel();
        restart_tittle = new javax.swing.JLabel();
        pause_button = new javax.swing.JPanel();
        pause_tittle = new javax.swing.JLabel();
        changeMap_button = new javax.swing.JPanel();
        changeMap_title = new javax.swing.JLabel();
        switch_ball_velocity = new javax.swing.JPanel();
        plusbVel_button = new javax.swing.JLabel();
        minusbVel_button = new javax.swing.JLabel();
        switch_bar_velocity = new javax.swing.JPanel();
        minusBVel_button = new javax.swing.JLabel();
        plusBVel_button = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        menuJuego_content.setBackground(new java.awt.Color(52, 52, 60));

        switch_BarVelocity_title.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        switch_BarVelocity_title.setForeground(new java.awt.Color(155, 155, 152));
        switch_BarVelocity_title.setText("Velocidad barra");

        switch_BallVelocity_title.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        switch_BallVelocity_title.setForeground(new java.awt.Color(155, 155, 152));
        switch_BallVelocity_title.setText("Velocidad bola");

        menu_title.setBackground(new java.awt.Color(155, 155, 152));

        menu_tittle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        menu_tittle.setText("Control");
        menu_title.add(menu_tittle);

        restart_button.setBackground(new java.awt.Color(155, 155, 152));

        restart_tittle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        restart_tittle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_videogame_80s/data/Icons/restart.png"))); // NOI18N
        restart_tittle.setText("Restart");
        restart_button.add(restart_tittle);

        pause_button.setBackground(new java.awt.Color(155, 155, 152));

        pause_tittle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        pause_tittle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_videogame_80s/data/Icons/pause.png"))); // NOI18N
        pause_tittle.setText("Pause");
        pause_button.add(pause_tittle);

        changeMap_button.setBackground(new java.awt.Color(155, 155, 152));

        changeMap_title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        changeMap_title.setText("Cambiar mapa");
        changeMap_button.add(changeMap_title);

        switch_ball_velocity.setBackground(new java.awt.Color(155, 155, 152));

        plusbVel_button.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        plusbVel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_videogame_80s/data/Icons/minus.png"))); // NOI18N
        switch_ball_velocity.add(plusbVel_button);

        minusbVel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_videogame_80s/data/Icons/plus.png"))); // NOI18N
        switch_ball_velocity.add(minusbVel_button);

        switch_bar_velocity.setBackground(new java.awt.Color(155, 155, 152));

        minusBVel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_videogame_80s/data/Icons/minus.png"))); // NOI18N
        switch_bar_velocity.add(minusBVel_button);

        plusBVel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_videogame_80s/data/Icons/plus.png"))); // NOI18N
        switch_bar_velocity.add(plusBVel_button);

        javax.swing.GroupLayout menuJuego_contentLayout = new javax.swing.GroupLayout(menuJuego_content);
        menuJuego_content.setLayout(menuJuego_contentLayout);
        menuJuego_contentLayout.setHorizontalGroup(
            menuJuego_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuJuego_contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeMap_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(menuJuego_contentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(menuJuego_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuJuego_contentLayout.createSequentialGroup()
                        .addComponent(restart_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(pause_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuJuego_contentLayout.createSequentialGroup()
                        .addGroup(menuJuego_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(switch_ball_velocity, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(switch_BallVelocity_title))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(menuJuego_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(switch_BarVelocity_title)
                            .addComponent(switch_bar_velocity, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        menuJuego_contentLayout.setVerticalGroup(
            menuJuego_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuJuego_contentLayout.createSequentialGroup()
                .addComponent(menu_title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(menuJuego_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(switch_BallVelocity_title)
                    .addComponent(switch_BarVelocity_title))
                .addGap(18, 18, 18)
                .addGroup(menuJuego_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(switch_ball_velocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switch_bar_velocity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(menuJuego_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pause_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restart_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(changeMap_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJuego_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJuego_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel changeMap_button;
    private javax.swing.JLabel changeMap_title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menuJuego_content;
    private javax.swing.JPanel menu_title;
    private javax.swing.JLabel menu_tittle;
    private javax.swing.JLabel minusBVel_button;
    private javax.swing.JLabel minusbVel_button;
    private javax.swing.JPanel pause_button;
    private javax.swing.JLabel pause_tittle;
    private javax.swing.JLabel plusBVel_button;
    private javax.swing.JLabel plusbVel_button;
    private javax.swing.JPanel restart_button;
    private javax.swing.JLabel restart_tittle;
    private javax.swing.JLabel switch_BallVelocity_title;
    private javax.swing.JLabel switch_BarVelocity_title;
    private javax.swing.JPanel switch_ball_velocity;
    private javax.swing.JPanel switch_bar_velocity;
    // End of variables declaration//GEN-END:variables
}
